/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { LibPostGet, LibPostGetInterface } from "../LibPostGet";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "kinship",
        type: "uint256",
      },
    ],
    name: "PostGetInteract",
    type: "event",
  },
];

const _bytecode =
  "0x602d6037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea164736f6c634300080b000a";

export class LibPostGet__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LibPostGet> {
    return super.deploy(overrides || {}) as Promise<LibPostGet>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LibPostGet {
    return super.attach(address) as LibPostGet;
  }
  connect(signer: Signer): LibPostGet__factory {
    return super.connect(signer) as LibPostGet__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibPostGetInterface {
    return new utils.Interface(_abi) as LibPostGetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibPostGet {
    return new Contract(address, _abi, signerOrProvider) as LibPostGet;
  }
}
